In [1]:
import os
import shutil
import json

In [2]:
train_folder = 'C:/Users/HP/Desktop/new_activity/human_activity_retrieval_dataset/train'  # Replace with the path to your train folder
labels_file = 'C:/Users/HP/Desktop/new_activity/human_activity_retrieval_dataset/train_image_info.json'

In [3]:
with open(labels_file, 'r') as f:
    labels_data = json.load(f)

# Create subfolders based on labels
for image_name, label in labels_data.items():
    label_folder = os.path.join(train_folder, str(label))  # Create a subfolder with the label name
    os.makedirs(label_folder, exist_ok=True)  # Create the subfolder if it doesn't exist
    image_path = os.path.join(train_folder, image_name)
    shutil.move(image_path, os.path.join(label_folder, image_name))  # Move the image to the corresponding subfolder

print("Subfolders created based on labels.")

Subfolders created based on labels.


In [4]:
label_counts = {}

# Iterate through subfolders in the "Train" directory
for label_folder in os.listdir(train_folder):
    if os.path.isdir(os.path.join(train_folder, label_folder)):
        # Count the number of files (images) in each label subfolder
        label_count = len(os.listdir(os.path.join(train_folder, label_folder)))
        label_counts[label_folder] = label_count

# Print the counts for each label
for label, count in label_counts.items():
    print(f"Label '{label}': {count} images")

Label 'calling': 763 images
Label 'clapping': 763 images
Label 'cycling': 763 images
Label 'dancing': 760 images
Label 'drinking': 763 images
Label 'eating': 764 images
Label 'fighting': 764 images
Label 'hugging': 762 images
Label 'laughing': 763 images
Label 'listening_to_music': 764 images
Label 'running': 764 images
Label 'sitting': 763 images
Label 'sleeping': 761 images
Label 'texting': 763 images
Label 'using_laptop': 763 images


In [7]:
validate_folder = 'C:/Users/HP/Desktop/new_activity/human_activity_retrieval_dataset/gallery'
labels1_file = 'C:/Users/HP/Desktop/new_activity/human_activity_retrieval_dataset/test_image_info.json'

In [8]:
with open(labels1_file, 'r') as f:
    labels_data = json.load(f)

# Create subfolders based on labels
for image_name, label in labels_data.items():
    label_folder = os.path.join(validate_folder, str(label))  # Create a subfolder with the label name
    os.makedirs(label_folder, exist_ok=True)  # Create the subfolder if it doesn't exist
    image_path = os.path.join(validate_folder, image_name)
    shutil.move(image_path, os.path.join(label_folder, image_name))  # Move the image to the corresponding subfolder

print("Subfolders created based on labels.")

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/HP/Desktop/new_activity/human_activity_retrieval_dataset/gallery\\Image_3280.jpg'

In [9]:
label_counts = {}

# Iterate through subfolders in the "Train" directory
for label_folder in os.listdir(train_folder):
    if os.path.isdir(os.path.join(train_folder, label_folder)):
        # Count the number of files (images) in each label subfolder
        label_count = len(os.listdir(os.path.join(train_folder, label_folder)))
        label_counts[label_folder] = label_count

# Print the counts for each label
for label, count in label_counts.items():
    print(f"Label '{label}': {count} images")

Label 'calling': 763 images
Label 'clapping': 763 images
Label 'cycling': 763 images
Label 'dancing': 760 images
Label 'drinking': 763 images
Label 'eating': 764 images
Label 'fighting': 764 images
Label 'hugging': 762 images
Label 'laughing': 763 images
Label 'listening_to_music': 764 images
Label 'running': 764 images
Label 'sitting': 763 images
Label 'sleeping': 761 images
Label 'texting': 763 images
Label 'using_laptop': 763 images


In [10]:
label_counts = {}

# Iterate through subfolders in the "Train" directory
for label_folder in os.listdir(validate_folder):
    if os.path.isdir(os.path.join(validate_folder, label_folder)):
        # Count the number of files (images) in each label subfolder
        label_count = len(os.listdir(os.path.join(validate_folder, label_folder)))
        label_counts[label_folder] = label_count

# Print the counts for each label
for label, count in label_counts.items():
    print(f"Label '{label}': {count} images")

Label 'calling': 67 images
Label 'clapping': 67 images
Label 'cycling': 67 images
Label 'dancing': 67 images
Label 'drinking': 67 images
Label 'eating': 66 images
Label 'fighting': 66 images
Label 'hugging': 67 images
Label 'laughing': 67 images
Label 'listening_to_music': 66 images
Label 'running': 66 images
Label 'sitting': 67 images
Label 'sleeping': 67 images
Label 'texting': 66 images
Label 'using_laptop': 67 images


In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import RMSprop
import matplotlib.pyplot as plt
import numpy as np
import cv2
from tensorflow.keras.optimizers import Adam
import os

In [2]:
train_datagen = ImageDataGenerator(
    rescale=1.0 / 255,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    
)

In [3]:
validation_datagen = ImageDataGenerator(rescale=1.0 / 255)
test_datagen = ImageDataGenerator(rescale=1.0 / 255)

In [4]:
train_generator = train_datagen.flow_from_directory(
    'C:/Users/HP/Desktop/new_activity/human_activity_retrieval_dataset/train',
    target_size=(150,150),
    batch_size=32,
    class_mode='categorical',  # Use 'categorical' for multi-class classification
    shuffle=True
)

Found 11443 images belonging to 15 classes.


In [5]:
train_generator.class_indices

{'calling': 0,
 'clapping': 1,
 'cycling': 2,
 'dancing': 3,
 'drinking': 4,
 'eating': 5,
 'fighting': 6,
 'hugging': 7,
 'laughing': 8,
 'listening_to_music': 9,
 'running': 10,
 'sitting': 11,
 'sleeping': 12,
 'texting': 13,
 'using_laptop': 14}

In [6]:
validation_generator = validation_datagen.flow_from_directory(
    'C:/Users/HP/Desktop/new_activity/human_activity_retrieval_dataset/gallery',
    target_size=(150,150),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

Found 1000 images belonging to 15 classes.


In [7]:
validation_generator.class_indices

{'calling': 0,
 'clapping': 1,
 'cycling': 2,
 'dancing': 3,
 'drinking': 4,
 'eating': 5,
 'fighting': 6,
 'hugging': 7,
 'laughing': 8,
 'listening_to_music': 9,
 'running': 10,
 'sitting': 11,
 'sleeping': 12,
 'texting': 13,
 'using_laptop': 14}

In [8]:
validation_generator.classes

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3

In [9]:
from tensorflow.keras.layers import Dropout,AveragePooling2D,BatchNormalization
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(128, activation='relu'))
model.add(Dense(15, activation='softmax')) 

In [10]:
model.compile(optimizer=Adam(learning_rate=0.0001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [11]:
len(train_generator)
len(validation_generator)

32

In [12]:
epochs = 40
history = model.fit(
    train_generator,
    epochs=epochs,
    steps_per_epoch=len(train_generator),
    validation_data=validation_generator
   )

Epoch 1/40
358/358 [==============================] - 675s 2s/step - loss: 2.7866 - accuracy: 0.1133 - val_loss: 3.5909 - val_accuracy: 0.0880
Epoch 2/40
358/358 [==============================] - 658s 2s/step - loss: 2.6131 - accuracy: 0.1410 - val_loss: 2.4137 - val_accuracy: 0.2130
Epoch 3/40
358/358 [==============================] - 656s 2s/step - loss: 2.5817 - accuracy: 0.1518 - val_loss: 2.4235 - val_accuracy: 0.2110
Epoch 4/40
358/358 [==============================] - 653s 2s/step - loss: 2.5384 - accuracy: 0.1604 - val_loss: 2.4247 - val_accuracy: 0.2010
Epoch 5/40
358/358 [==============================] - 653s 2s/step - loss: 2.5169 - accuracy: 0.1710 - val_loss: 2.4297 - val_accuracy: 0.1980
Epoch 6/40
358/358 [==============================] - 649s 2s/step - loss: 2.4995 - accuracy: 0.1730 - val_loss: 2.4166 - val_accuracy: 0.2230
Epoch 7/40
358/358 [==============================] - 650s 2s/step - loss: 2.4671 - accuracy: 0.1895 - val_loss: 2.3666 - val_accuracy: 0.2160

In [55]:
validation_images = []  # Store only the images, not labels

for i in range(len(validation_generator)):
    batch_images, _ = validation_generator[i]  # Ignore the labels
    validation_images.extend(batch_images)

validation_images = np.array(validation_images)

In [56]:
query_image_files = sorted(os.listdir('C:/Users/HP/Desktop/new_activity/human_activity_retrieval_dataset/query_images'))
query_images = []

In [57]:
def load_and_preprocess_image(image_path, target_size=(150, 150)):
    # Open the image using PIL
    image = Image.open(image_path)

    # Resize the image to the target size
    image = image.resize(target_size)

    # Convert the image to a NumPy array
    image_array = np.array(image)

    # Normalize the pixel values to the range [0, 1]
    image_array = image_array / 255.0

    return image_array

    # Convert the image to a NumPy array
   

In [58]:
from PIL import Image
import numpy as np

for image_file in query_image_files:
    image_path = os.path.join('C:/Users/HP/Desktop/new_activity/human_activity_retrieval_dataset/query_images', image_file)
    image = load_and_preprocess_image(image_path)  # You need to define 'load_and_preprocess_image' for your preprocessing
    query_images.append(image)

query_images = np.array(query_images)

In [59]:
query_features = model.predict(query_images)
validation_features = model.predict(validation_images)

In [60]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(query_features, validation_features)


In [61]:
sorted_indices = np.argsort(similarity_matrix, axis=1)[:, ::-1]

In [62]:
K_values = [1, 10, 50]
mAP_values = []
mean_rank_values = []

In [78]:
for K in K_values:
    average_precision_list = []
    rank_list = []

    for i in range(len(query_features)):
        relevant_indices = sorted_indices[i][:K]
        
        
        if len(relevant_indices) > 0:
            precision = len(set(relevant_indices) & set(np.arange(len(validation_features)))) / K
        else:
            precision = 0  # No relevant images, set precision to 0

        average_precision_list.append(precision)
    # Calculate rank of the first relevant image
        if len(relevant_indices) > 0:
            try:
                rank = np.where(relevant_indices == i)[0][0] + 1  # Adding 1 to make it rank starting from 1
            except IndexError:
                rank = -1# Adding 1 to make it rank starting from 1
        else:
            rank = -1  # Indicate that there were no relevant images found

        rank_list.append(rank)
       

    mAP = np.mean(average_precision_list)
    mean_rank = np.mean(rank_list)

    mAP_values.append(mAP)
    mean_rank_values.append(mean_rank)
    
for i, K in enumerate(K_values):
    print(f"Mean Average Precision (mAP) at K={K}: {mAP_values[i]}")
print(f"Mean Rank: {mean_rank_values[0]}")  # Mean rank at K=1

Mean Average Precision (mAP) at K=1: nan
Mean Average Precision (mAP) at K=10: nan
Mean Average Precision (mAP) at K=50: nan
Mean Rank: -1.0


In [47]:
for i, K in enumerate(K_values):
    print(f"Mean Average Precision (mAP) at K={K}: {mAP_values[i]}")
print(f"Mean Rank: {mean_rank_values[0]}")  # Mean rank at K=1

Mean Average Precision (mAP) at K=1: nan
Mean Average Precision (mAP) at K=10: nan
Mean Average Precision (mAP) at K=50: nan
Mean Rank: -1.0


In [48]:
print(validation_features)

[[1.0770833e-01 6.8902582e-02 5.9580227e-04 ... 1.7693467e-01
  5.4085188e-02 4.1826494e-02]
 [5.5764828e-02 7.1228094e-02 6.3310362e-02 ... 7.0554428e-02
  6.0076464e-02 7.4670836e-02]
 [1.4027609e-01 3.0539636e-02 2.5981801e-05 ... 3.4929033e-02
  1.1239054e-01 1.4982983e-02]
 ...
 [6.9642045e-02 3.1698562e-02 2.3076185e-03 ... 1.8860847e-01
  9.8260209e-02 1.5373877e-01]
 [1.2301766e-01 9.3842708e-02 2.2383183e-02 ... 5.8000654e-02
  8.3940268e-02 1.0684829e-01]
 [5.3144056e-02 4.4655584e-02 3.0137664e-03 ... 2.7292389e-01
  8.7867789e-02 9.0973161e-02]]


In [49]:
print(query_features)

[[1.32662123e-02 1.35967704e-02 1.20445915e-01 ... 5.26958369e-02
  2.62192730e-02 2.73709986e-02]
 [1.25853404e-01 2.13938095e-02 1.89761622e-07 ... 6.03667498e-02
  1.08799838e-01 2.45150854e-03]
 [8.92514735e-02 3.68898027e-02 2.64728093e-04 ... 6.84010014e-02
  9.70216617e-02 2.44668096e-01]
 ...
 [6.76123018e-04 1.23793876e-03 7.43879795e-01 ... 4.99373442e-03
  4.53432993e-04 1.20086852e-03]
 [3.96197140e-02 5.82475141e-02 1.20215215e-01 ... 3.71358953e-02
  4.50914502e-02 6.72773942e-02]
 [4.62460555e-02 1.08941048e-01 1.07501512e-02 ... 7.00074434e-03
  1.72030963e-02 6.61382871e-03]]


In [50]:
dir_path = 'C:/Users/HP/Desktop/new_activity/human_activity_retrieval_dataset/query_images'

In [54]:
from keras.preprocessing.image import load_img
for i in os.listdir(dir_path):
    img = image.load_img(dir_path+'//'+i)
    plt.imshow(img)
    plt.show()

AttributeError: 'numpy.ndarray' object has no attribute 'load_img'

In [65]:
print(relevant_indices)

[119 212 224 694 243 120 219 216 411  77  86 726 239  57 463 240 105 214
 202 226 231 251 265 433 109 454 123 737 222 210 456 408 213  93 447 111
 402 254 256 267 762 491 217 260 225 738  40 549 459 234]


In [68]:
len(validation_features)

1000

In [72]:
print(sorted_indices)

[[205 179 669 ... 558 565 581]
 [495 532 479 ... 675 176 186]
 [637 645 970 ... 675 176 186]
 ...
 [185 266 154 ... 558 565 581]
 [604 193 317 ... 565 579 581]
 [119 212 224 ... 186 849 853]]


In [73]:
print(similarity_matrix)

[[0.23751208 0.7685994  0.13853477 ... 0.32007077 0.44089696 0.30534503]
 [0.8134743  0.4507754  0.8985771  ... 0.62480265 0.61458856 0.5898712 ]
 [0.7719487  0.6335418  0.73989666 ... 0.87955254 0.8390167  0.7074755 ]
 ...
 [0.0178176  0.34022805 0.00553497 ... 0.03331408 0.12786816 0.03198443]
 [0.6325407  0.90917534 0.5285223  ... 0.6583277  0.8126109  0.5398518 ]
 [0.20549628 0.4276697  0.14726873 ... 0.22003584 0.33624277 0.25943616]]


In [74]:
print(model)

In [75]:
print(query_images)

[[[[0.70980392 0.7372549  0.77647059]
   [0.69411765 0.72156863 0.76078431]
   [0.6745098  0.70196078 0.74117647]
   ...
   [0.76078431 0.80392157 0.82745098]
   [0.75686275 0.8        0.82352941]
   [0.75686275 0.8        0.82352941]]

  [[0.72941176 0.75686275 0.79607843]
   [0.71372549 0.74117647 0.78039216]
   [0.69803922 0.7254902  0.76470588]
   ...
   [0.76078431 0.80392157 0.82745098]
   [0.75686275 0.8        0.82352941]
   [0.75686275 0.8        0.82352941]]

  [[0.75686275 0.78431373 0.81568627]
   [0.74509804 0.77254902 0.80392157]
   [0.72941176 0.75686275 0.78823529]
   ...
   [0.75686275 0.79607843 0.83137255]
   [0.75686275 0.79607843 0.83137255]
   [0.75686275 0.79607843 0.83137255]]

  ...

  [[0.75294118 0.74117647 0.71372549]
   [0.76862745 0.75686275 0.72941176]
   [0.77647059 0.76470588 0.7372549 ]
   ...
   [0.78039216 0.78039216 0.74901961]
   [0.79215686 0.78823529 0.76862745]
   [0.8        0.79607843 0.77647059]]

  [[0.73333333 0.73333333 0.70196078]
   [0.7

In [76]:
print(query_features)

[[1.32662123e-02 1.35967704e-02 1.20445915e-01 ... 5.26958369e-02
  2.62192730e-02 2.73709986e-02]
 [1.25853404e-01 2.13938095e-02 1.89761622e-07 ... 6.03667498e-02
  1.08799838e-01 2.45150854e-03]
 [8.92514735e-02 3.68898027e-02 2.64728093e-04 ... 6.84010014e-02
  9.70216617e-02 2.44668096e-01]
 ...
 [6.76123018e-04 1.23793876e-03 7.43879795e-01 ... 4.99373442e-03
  4.53432993e-04 1.20086852e-03]
 [3.96197140e-02 5.82475141e-02 1.20215215e-01 ... 3.71358953e-02
  4.50914502e-02 6.72773942e-02]
 [4.62460555e-02 1.08941048e-01 1.07501512e-02 ... 7.00074434e-03
  1.72030963e-02 6.61382871e-03]]
